OBJS := \
	main.o \

LIBS := \
	-lpthread \
	-lGL \
	-lSDL \
	-lSDL_image \
	-lSDL_ttf \
	-ldl \
	-ldebug \

INCSDIR := \
	$(ROOT_DIR)/debug \

GCC_COMMON_FLAGS := \
	-g \

TARGET := open_visual_studio.elf

include $(MKSCRIPTS)/build.mk
